[package]
name = "lh"
version = "0.1.0"
edition = "2021"
description = "List handsomely customizable ls command work in progress" 
license = "MIT"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
